$kind: http-request
description: Soft-delete a role record. The record is not permanently removed. Restore it with the corresponding `POST /roles/{{role_id}}/restore` request.
url: "{{baseUrl}}/v1/roles/:role_id"
method: DELETE
pathVariables:
  - key: role_id
    value: "{{role_id}}"
    $type: |-
      {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          }
        },
        "required": [
          "value"
        ]
      }
body:
  type: text
  content: ""
order: 3000
